name: Build

on: [push]

jobs:
  test:
    name: Run pythagors build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Prepare cargo toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Prepare cache
        uses: Swatinem/rust-cache@v1
      - name: Build project
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Check with Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
