name: Build

on: [push]

jobs:
  test:
    name: Run pythagors build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v5
      - name: Prepare rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Prepare just
        uses: extractions/setup-just@v3
      - name: Build app
        run: just build
      - name: Check with Clippy
        run: just lint
