name: Build

on: [push]

jobs:
  test:
    name: Run pythagors build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Prepare rust toolchain
        uses: actions-rs/toolchain@v1
      - name: Build app
        run: cargo build
      - name: Check with Clippy
        run: cargo clippy -- -D warnings
