name: Test

on: [push]

jobs:
  test:
    name: Run pythagors tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf-compiler libprotobuf-dev 
          version: 1.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install binstall plugin
        uses: actions-rs/cargo@v1
        with:
          command: install cargo-binstall
      - name: Install shuttle plugin
        uses: actions-rs/cargo@v1
        with:
          command: binstall cargo-shuttle
      - name: Tests run
        uses: actions-rs/cargo@v1
        with:
          command: test
